### ISSUE TITLE
Zoomed video moving toggle video playback

### ISSUE THREAD

**Issue by notramo** [zaps166/QMPlay2#143]
First, thanks for quickly solving #140.
There is a setting option *Left mouse button on video dock toggles playback*.
If this is set, moving the zoomed video is a bit weird, because when the mouse button is released after moving, the playback start/stop.

**Comment by zaps166** [comment]
Fixed :)

**Comment by notramo** [comment]
It's partially fixed yet.
If the modifier was released earlier than the mouse button, the playback start/stop when the mouse button is released.
Also, if the mouse button is clicked without the modifier (that should toggle playback), but the modifier was pressed down before releasing the mouse button, it neither toggle playback or move video.

**Comment by zaps166** [comment]
Fixed: aa5c84a3978bbbdd06161b9726394e4967bb77b6

**Comment by notramo** [comment]
Thanks!
